using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;
using BaiTapThem.ViewModel;

namespace BaiTapThem.View
{
    /// <summary>
    /// Interaction logic for ImportOOP.xaml
    /// </summary>
    public partial class ImportOOP : Window
    {
        public ImportOOPViewModel viewModel { get; set; }

        public ImportOOP()
        {
            InitializeComponent();
            this.DataContext = new ImportOOPViewModel();
            //viewModel = new ImportOOPViewModel();
            //this.DataContext = viewModel;
            //viewModel.DataGrid = myDataGrid;
        }

        //private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        //{
        //    var dataGrid = sender as DataGrid;

        //    //var viewModel = dataGrid.DataContext as ImportOOPViewModel;

        //    if (viewModel == null || viewModel.Headers == null) return;

        //    // Xóa cột mặc định
        //    dataGrid.Columns.Clear();

        //    foreach (var header in viewModel.Headers)
        //    {
        //        dataGrid.Columns.Add(new DataGridTextColumn
        //        {
        //            Header = header,
        //            Binding = new Binding(header) // Binding trực tiếp thuộc tính của lớp Person
        //        });
        //    }
        //    //// Xóa hàng cũ trước khi thêm mới
        //    //dataGrid.Items.Clear();

        //    // Thêm từng instance Person vào DataGrid
        //    //foreach (var person in viewModel.Persons)
        //    //{
        //    //    dataGrid.Items.Add(person);
        //    //}
        //}
    }
}